### PR TITLE
allow specifying the member-order

### LINKED ISSUE #34: Documenting class methods / attributes in `bysource` order
Hi there! First of all, let me say that this is a great extension, and it's come in handy in a project I am working on.

I have a question about ordering class members in the TOC for each class. When I use `member-order: "bysource"` and have `autosummary: True` in my `autodoc_default_options`, I notice that my module TOC is ordered by source, but the members in my classes are ordered alphabetically instead. Is there a way to specify `bysource` ordering for class members as well?

If it is any help, I am using `autodocsumm==0.2.1`

Thanks!

### PR DESCRIPTION
**Pull request by Chilipp**
hey @btjanaka,

my apologies for coming back to you so late and thanks for submitting your issue! Your request should be fixed with this PR.

closes #34

### CODE REVIEW

**Comment by btjanaka** [comment]
Hi @Chilipp , thanks for the reply! I'll try out the fix shortly.

**Comment by btjanaka** [comment]
Looks like the fix works! Thanks a bunch.

If this is merged, how soon can I expect to see it on PyPI? (sorry if I sound a bit pushy :grimacing:)

**Comment by Chilipp** [comment]
thanks for the confirmation @btjanaka! I'd like to merge the remaining open PRs and make a new release. So it should be available tomorrow

**Comment by Chilipp** [comment]
done @btjanaka: https://pypi.org/project/autodocsumm/0.2.2/ and https://github.com/Chilipp/autodocsumm/releases/tag/v0.2.2

conda-forge will come soon.

**Pull request merged**
