### PR TITLE
Allow Sphinx v6

### PR DESCRIPTION
**Pull request by lafrech**
Copied on https://github.com/Chilipp/autodocsumm/pull/79.

I'd only test against each supported Sphinx major version, but that's not my call.

### CODE REVIEW

**Comment by lafrech** [comment]
Sphinx 6 dropped Python 3.7.

I reworked the test matrix. @Chilipp feel free to close this and define the test matrix you find appropriate.

**Comment by Chilipp** [comment]
Thanks @lafrech !

**Comment by stinodego** [comment]
@Chilipp Would be great if a new release could be made that includes this commit!

**Comment by Chilipp** [comment]
done on pypi @stinodego `conda-forge` will come within the next 24 hours

**Comment by stinodego** [comment]
Amazing! Thanks for the quick action ❤️

**Pull request merged**
