### PR TITLE
Allow disabling nesting of autosummary tables 

### LINKED ISSUE #19: Apply autosummary for module but not nested classes
I'm using autodocsumm along with sphinx-apidoc to generate documentation.

My current usage is as follows:
```
.. automodule:: {{ pkgname }}
   :members:
   :undoc-members:
   :inherited-members:
   :autosummary:
```

This creates the summary table as desired for the module, but also causes each class etc. in the package added by automodule to have a summary table, which is not desired. Is there an easy way I can get just the summary table for the module, and not for nested structures?

### PR DESCRIPTION
**Pull request by piyushk**
I've opened a draft PR for allowing disabling of nesting of autosummary tables. The use case is described in #19 

Closes #19, #13 

Once we finalize on the solution, I can add the necessary tests.

### CODE REVIEW

**Comment by Chilipp** [comment]
👍 Looks great! Thanks a lot! We should add some tests here to verify it works. If you want, I can do this quickly tomorrow

**Comment by Chilipp** [comment]
It simply requires an rst file in the [sphinx_supp](https://github.com/Chilipp/autodocsumm/tree/master/tests/sphinx_supp) directory and a small test method the checks it in [test_autodocsumm.py](https://github.com/Chilipp/autodocsumm/blob/master/tests/test_autodocsumm.py)

**Comment by piyushk** [comment]
Sounds good. I can add the test/documentation tomorrow and update this PR.

I'll also submit a new PR that rehashes #13 since that solution is necessary to prevent warnings from sphinx, as we treat warnings as errors.

**Comment by piyushk** [comment]
@Chilipp: The PR is now ready for review.

**Comment by piyushk** [comment]
I've also added a fix that subsumes #13 using versions, since sphinx-doc/sphinx#6475 was merged and released in version 2.2, and `add_autodocumenter` has been available since version 0.6.

That change stops warnings from being generated starting with sphinx version 2.2, as we treat warnings as errors in our setup.

**Comment by Chilipp** [comment]
Hey @piyushk! This is really great, thanks a lot for this nice implementation! It looks all good to me and I only added some minor changes in the RST documentations (https://github.com/Chilipp/autodocsumm/pull/20/commits/46998d4afb4c7d6363fae90953f6dcc9b2f78a87 and https://github.com/Chilipp/autodocsumm/pull/20/commits/fe6da6befb1eb41a99c0e242803719eb4ad7c3be). Also thanks a lot for implementing the proposed changes from https://github.com/Chilipp/autodocsumm/pull/13!

I will merge this PR when the CI finishes and make a new release tomorrow.

**Comment by piyushk** [comment]
Thanks! The changes look good. I appreciate the quick turnaround and release.

**Comment by Chilipp** [comment]
Alright, new release is published ([v0.1.11](https://github.com/Chilipp/autodocsumm/releases/tag/v0.1.11)) and uploaded to [PyPi](https://pypi.org/project/autodocsumm/). [conda-forge](anaconda.org/conda-forge/autodocsumm) should be finished later today.

Thank you very much again for your work on this!

**Pull request merged**
