### PR TITLE
Declare project and pytest configuration in pyproject.toml

### PR DESCRIPTION
**Pull request by EpicWink**
Uses PEP 518 and PEP 621. Drops support for Python 3.6 and running tests via `python setup.py`.

setup.py-less editable installs are blocked by pypa/setuptools#3082 (likely setuptools v64), so a stub setup.py remains.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
@EpicWink I believe it would be possible to do the main part of this provided that you leave a stup setup.py file around https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/?highlight=660#editable-installation even without setuptools supporting pep660. How do you think about that

**Comment by Chilipp** [comment]
I agree to @jenshnielsen, we should still keep a `setup.py` file unless you can give me a good reason why it should be removed. What do you think @EpicWink ?

**Comment by EpicWink** [comment]
Sounds good, I'll get to it tomorrow and test

**Review by Chilipp — APPROVED** [review]
thanks a lot @EpicWink!

**Pull request merged**
